# Generated by Django 3.1.7 on 2021-03-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='qualifications',
        ),
    ]
