# Generated by Django 3.1.7 on 2021-03-05 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('listing_title', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(blank=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
