# Generated by Django 3.1.7 on 2021-03-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_enrolled', '0002_auto_20210305_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name_plural': 'Enrollments'},
        ),
        migrations.RenameField(
            model_name='enrolled',
            old_name='listing_id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='enrolled',
            old_name='listing_title',
            new_name='class_title',
        ),
    ]
