# Generated by Django 3.1.7 on 2021-03-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_enrolled', '0003_auto_20210305_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name': 'Student Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
    ]
